#!/usr/bin/env ruby

require 'pathname'
require 'optparse'
require 'stringio'
require 'time'

__file = File.symlink?(__FILE__) ? File.readlink(__FILE__) : __FILE__
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', __file)
require 'bundler/setup'
require 'pry'
require 'octokit'

require 'time-lord' # nb: this monkey-patches Time/Numeric classes a lot

# Monkey-patch time-lord gem as it doesn't round values by default, instead relying on Integer#/(Integer) which results in effectively a floor() operation. Over intervals of, say, 1.9 years, seeing just "1 year" as the output is rather misleading.
module TimeLord
  class Scale
    def count(unit)
      rounding_scale = unit >= YEAR ? 1 : 0
      rounding_factor = 10 ** rounding_scale
      if rounding_factor > 1
        (absolute.to_f * rounding_factor / unit).round.to_f / rounding_factor
      else
        (absolute.to_f / unit).round
      end
    end

    def plurality?(count)
      (1 - count).abs > 0.1
    end
  end
end

module HelperMethods
  def system(*command)
    STDERR.puts "  > #{command.join(' ')}"
    Kernel.system(*command)
  end

  def prompt(ask)
    STDERR.print(ask << ' ')
    STDIN.gets.chomp.downcase[0] == 'y'
  end

  def format_time(t)
    t.ago.to_words
  end

  def committer(commit)
    return commit.author.login if commit.author

    '%s &lt;%s&gt;' % [commit.commit.author.name, commit.commit.author.email]
  end

  def link_to(url, text)
    '[%s](%s)' % [text, url]
  end
end

class RepoList
  def self.load_from_file(filename)
    new(Marshal.load(File.read(filename)))
  end

  def initialize(repos_from_cache)
    @cached_repos = repos_from_cache
  end
  attr_reader :cached_repos

  def repos
    cached_repos.map { |data|
      gh_repo, last_commit, files_in_root = data.values_at(:repo, :last_commit, :files_in_root)
      Repo.new(gh_repo) { |repo|
        repo.last_commit = last_commit
        repo.files_in_root = files_in_root
      }
    }
  end
end

class ReportBuilder
  include HelperMethods

  def initialize(repos:, rules:)
    @repos = repos
    @rules = rules
  end
  attr_reader :repos, :rules

  def prepare
    return if @_prepared
    repos.each do |repo|
      rules.each do |rule|
        rule.visit(repo)
      end
    end
    validate
    @_prepared = true
  end

  def validate
    @repos.group_by(&:new_name).each do |(new_name, repos)|
      if repos.length > 1
        warn "WARNING: Naming conflict! Multiple repos are recommended to be renamed to `#{new_name}`: #{repos.map(&:name).join(', ')}"
      end
    end

    if @error
      warn "An Error occurred"
      exit 1
    end
  end

  def write(output)
    prepare

    output.puts "# repos"

    repos.each do |repo|
      # next if repo.fork?
      source = StringIO.new
      source << "## #{link_to(repo.html_url, repo.name)}"
      source << ' &#128274;' if repo.private
      if repo.name != repo.new_name
        source << " => `#{repo.new_name}`"
      end
      source << "\n\n"

      repo.observations.each do |obs|
        source.puts "- #{obs}"
      end

      recs = distill_recommendations(repo.recommendations)
      recs.unshift('Rename as indicated') if repo.name != repo.new_name

      if recs.any?
        source.puts '- Recommendations:'
        recs.each do |rec|
          source.puts "  - #{rec}"
        end
      end

      output.puts source.string
      output.puts
    end
  end

  def distill_recommendations(recommendations)
    return [] if recommendations.empty?

    translate_recommendations(sort_recommendations(recommendations.uniq)[0,1]).compact
  end

  def sort_recommendations(recs)
    recs.sort { |a,b|
      case a
      when :keep, :more_evaluation_required
        -1
      when :safe_to_archive
        if b == :keep
          1
        else
          -1
        end
      when :delete, :archive
        1 # delete should always be sorted to the end so others can override
      when :evaluate_fork_for_deletion
        if b == :delete
          -1
        else
          1
        end
      else
        0
      end
    }
  end

  def translate_recommendations(recs)
    recs.map { |r|
      case r
      when :more_evaluation_required
        "Investigate further"
      when :safe_to_archive, :archive
        "Archive"
      when :keep
        nil
      when :delete
        "Delete or Archive"
      when :evaluate_fork_for_deletion
        "Fork; Investigate further and delete if not in use"
      when String
        r
      else
        fail "Define message for symbol recommendation #{r.inspect}"
      end
    }
  end

end

class Repo
  def initialize(gh_repo, &block)
    @gh_repo = gh_repo
    @new_name = gh_repo.name
    block.call(self)
    @recommendations = []
    @observations = []
  end

  attr_reader :recommendations, :observations
  attr_accessor :last_commit, :new_name, :files_in_root

  def method_missing(*args, &block)
    @gh_repo.send(*args, &block)
  end

  def description?
    !description.empty?
  end

  def description
    @gh_repo.description.to_s
  end

  def fork?
    !!@gh_repo.to_attrs[:fork]
  end

  def has_gemspec?
    files_in_root.any? { |file| file.name.end_with?('.gemspec') }
  end
end

module Rules
  class Base
    include HelperMethods

    def matches?(repo)
      false
    end

    def visit(repo)
      return false unless matches?(repo)
      repo.observations.concat(Array(observations(repo)))
      repo.recommendations.concat(Array(recommendations(repo)))
      true
    end

    def recommendations(repo)
      nil
    end

    def observations(repo)
      nil
    end
  end

  class ReallyOld < Base
    def initialize(max_age)
      @before_date = Time.now - max_age
    end

    def matches?(repo)
      repo.pushed_at < @before_date
    end

    def recommendations(repo)
      :archive
    end

    def observations(repo)
      # 'Not updated recently'
    end
  end

  class LastUpdated < Base
    def matches?(repo)
      true
    end

    def observations(repo)
      link_to(repo.last_commit.html_url, "Last updated #{format_time(repo.pushed_at)} by #{committer(repo.last_commit)}")
    end
  end

  class Describe < Base
    def matches?(repo)
      repo.description?
    end

    def observations(repo)
      "Description:\n> #{repo.description}"
    end
  end

  class Legacy < Base
    def matches?(repo)
      repo.new_name.start_with?('legacy-') || (repo.description.downcase.include?('legacy') && !repo.description[/in.?use/])
    end

    def recommendations(repo)
      :archive
    end
  end

  class Fork < Base
    def matches?(repo)
      repo.fork?
    end

    def observations(repo)
      "**fork** of #{link_to(repo.parent.html_url, repo.parent.full_name)}"
    end

    def recommendations(repo)
      :evaluate_fork_for_deletion
    end
  end

  class PatternMatch < Base
    def initialize(name: nil, description: nil, recommendations: nil, observations: nil)
      fail ArguementError unless name || description and recommendations || observations
      @name_pattern = name
      @description_pattern = description
      @recommendations = recommendations
      @observations = observations
    end

    def matches?(repo)
      @name_pattern && @name_pattern.match(repo.new_name) or @description_pattern && @description_pattern.match(repo.description)
    end

    def observations(repo)
      @observations
    end

    def recommendations(repo)
      @recommendations
    end
  end

  class Namespace < Base
    def initialize(name_pattern:, namespace:)
      @name_pattern = name_pattern
      @namespace = namespace
    end

    def matches?(repo)
      @name_pattern.match(repo.new_name)
    end

    def visit(repo)
      super(repo) or return
      repo.new_name = "#{@namespace}-#{repo.new_name}"
    end
  end

  class Rename < Base
    def initialize(pattern, replacement)
      @pattern, @replacement = pattern, replacement
    end

    def matches?(repo)
      @pattern.match(repo.new_name)
    end

    def visit(repo)
      super(repo) or return
      repo.new_name = repo.new_name.gsub(@pattern, @replacement)
    end
  end

  class GemRepoRename < Rename
    def matches?(repo)
      repo.has_gemspec?
    end
  end

  class Downcase < Base
    def matches?(repo)
      true
    end

    def visit(repo)
      super(repo) or return
      repo.new_name = repo.new_name.downcase
    end
  end
end

@rules = [
  Rules::LastUpdated.new,
  Rules::Describe.new,
  Rules::ReallyOld.new(3.years),
  Rules::Legacy.new,
  Rules::Fork.new,

  Rules::PatternMatch.new(name: /\A(Android-GoodGuide-(App|SDK))\z/i, recommendations: :more_evaluation_required),

  Rules::GemRepoRename.new(/\A(.+?)(?:-gem)?\z/, '\1-gem'),

  Rules::Downcase.new,
  Rules::Rename.new(/_/, '-'), # stop using underscores in repo names, to avoid any further confusion

  Rules::Rename.new(/\Agoodguide-(.+)\z/, '\1'),
  Rules::Rename.new(/\Aplatform\z/, 'purview-www'),
  Rules::Rename.new(/\Aplatform-(.+)\z/, 'purview-\1'),
  Rules::Rename.new(/\Aconsumer-(.+)\z/, 'goodguide-\1'),
  Rules::Rename.new(/\Aandroid-goodguide-(.+)\z/i, 'goodguide-android-\1'),
  Rules::Rename.new(/\Asolr-goodguide-config\z/i, 'goodguide-solr-config'),
  Rules::Rename.new(/\Aios-consumer-data-analysis\z/i, 'goodguide-ios-data-analysis'),
  Rules::Rename.new(/\Anlp.+api\z/i, 'nlpapi'),
  Rules::Rename.new(/\Adocker-(mysql.+)\z/i, 'dockerfile-\1'),
  Rules::Rename.new(/\Ahorde-gem\z/i, 'horde'),

  Rules::Namespace.new(name_pattern: /\A(accounts|amazon-earth-day|extension|www|api|nlpapi|ios|users-service|content|(accounts(-internal)?|nlpapi|content|api)-gem|public-api)\z/, namespace: 'goodguide'),

  Rules::Namespace.new(name_pattern: /\A(dolt|dorc|dimwit|buffoon|dingbat|muppeteer)/, namespace: 'ratings'),


  Rules::Namespace.new(name_pattern: /\A(platform)|\A(target-products|rules|regression-tests)\z/, namespace: 'purview'),

  Rules::Namespace.new(name_pattern: /\A(deploy|hubot|chef|cookbooks|git-hooks|(health|assets|pricegrabber|product-soup|scraper|visualizations|matching|packrat|release-tracker|releasinator)-gem)\z/, namespace: 'gg'),

  Rules::PatternMatch.new(description: /\b(ARCHIVE|DEPRECATED)\b/i, recommendations: :safe_to_archive),
  Rules::PatternMatch.new(name: /\A(gg-deploy)\z/, recommendations: :keep),
  Rules::PatternMatch.new(description: /in.use/, recommendations: :keep),

  Rules::PatternMatch.new(name: /\bspike\b/, description: /hack|experiment|w\.?i\.?p\.?|temporary/i, recommendations: :safe_to_archive),
  Rules::PatternMatch.new(name: /style-guide/i, recommendations: 'Valid to keep around if we review the rules'),

  Rules::PatternMatch.new(name: /\A(jenkins)\z/i, recommendations: :keep),

  Rules::PatternMatch.new(name: /\Apurview-rules\z/i, recommendations: :safe_to_archive),
  Rules::PatternMatch.new(name: /\Ascorecard\z/i, recommendations: 'Talk to Bill about this.'),

  Rules::PatternMatch.new(name: /\Ahorde/i, recommendations: :safe_to_archive),
  Rules::PatternMatch.new(name: /\Aprezto\z/i, recommendations: 'Used by `dotfiles` repo. Evalutate if that is worth keeping around and if we still need to have a fork of prezto as well.'),
]

repo_data_filename = ARGV[0] or fail 'You must pass a filename to load repo data (use ./load_all_github_repos)'

@repolist = RepoList.load_from_file(repo_data_filename)

@builder = ReportBuilder.new(repos: @repolist.repos, rules: @rules)
@builder.prepare
@builder.write(STDOUT)
